#!/usr/bin/env bash
# A bash script that displays "To infinity and beyond" indefinitely but
# display "I am invincible!!!" when receiving a SIGTERM signal

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done
