#!/usr/bin/env bash
# This displays "Best school" 10 times but "bad luck" at 4th and "good luck" at 8th

i=0
while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 3 ]; then
		echo "bad luck"
	elif [ "$i" -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
